<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="qsp" ignored="0" name="Test2" tests="1" failures="0" timestamp="17 Mar 2018 07:51:33 GMT" time="3.873" errors="0">
  <testcase name="@BeforeMethod preCondition" time="3.869" classname="generic.BaseTest">
    <failure type="java.io.FileNotFoundException" message="C:\Users\admin\Desktop\testData.xls (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: C:\Users\admin\Desktop\testData.xls (The process cannot access the file because it is being used by another process)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.apache.poi.poifs.nio.FileBackedDataSource.newSrcFile(FileBackedDataSource.java:161)
	at org.apache.poi.poifs.nio.FileBackedDataSource.<init>(FileBackedDataSource.java:64)
	at org.apache.poi.poifs.filesystem.NPOIFSFileSystem.<init>(NPOIFSFileSystem.java:219)
	at org.apache.poi.poifs.filesystem.NPOIFSFileSystem.<init>(NPOIFSFileSystem.java:167)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:254)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:226)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:205)
	at generic.Excel.readData(Excel.java:15)
	at generic.BaseTest.preCondition(BaseTest.java:35)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod preCondition -->
  <testcase name="@AfterMethod postCondition" time="0.0" classname="generic.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterMethod postCondition -->
  <testcase name="validLogin" time="0.0" classname="script.TestScript">
    <skipped/>
  </testcase> <!-- validLogin -->
</testsuite> <!-- Test2 -->
